version: '3.8'

services:
  app:
    build: .
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./data:/data
    command: poetry run python -m {{cookiecutter.project_slug}}.main
